language: go
sudo: false

matrix:
  include:
    - go: 1.7
    - go: 1.8
    - go: 1.9
    - go: tip
  allow_failures:
    - go: tip

script:
  - go get -d -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./...)
  - go test -v -cover ./...