language: go
sudo: false

notifications:
  email:
    recipients:
      - boris@yonchev.me
    on_success: never
    on_failure: change

matrix:
  include:
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

install:
  - go get -d -t -v ./...

script:  
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./...)
  - go test -v -cover -race ./...